name: Minute Quote Update

on:
  schedule:
    - cron: '* * * * *'  # Run every minute
  workflow_dispatch:      # Allow manual trigger

jobs:
  update-quote:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Run update script
      run: python update.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add daily.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update quote - $(date +%Y-%m-%d_%H:%M)"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}